<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Battleship.Model</AssemblyName>
    <RootNamespace>Vsite.Oom.Battleship.Model</RootNamespace>
  </PropertyGroup>

</Project>
