<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Battleship.Tests">
	    <HintPath>bin\Debug\net8.0\Battleship.Tests.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>