# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore Model/Model.csproj && dotnet restore ModelTests/ModelTests.csproj
    - name: Build
      run: dotnet build Model/Model.csproj --no-restore && dotnet build ModelTests/ModelTests.csproj --no-restore
    - name: Test
      run: dotnet test ModelTests/ModelTests.csproj --no-build --verbosity normal
